create table permissao_grupo (permissao_id bigint not null, grupo_id bigint not null) engine=InnoDB;
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null) engine=InnoDB;
create table tab_cidade (id bigint not null auto_increment, nome varchar(255), estado_id bigint not null, primary key (id)) engine=InnoDB;
create table tab_cozinha (id bigint not null auto_increment, observacao varchar(255), nom_cozinha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tab_estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table tab_forma_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table tab_grupo (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table tab_permissao (id bigint not null auto_increment, descricao varchar(255), nom_permissao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tab_produto (id bigint not null auto_increment, ativo bit, descricao varchar(255), preco decimal(19,2), produto_restaurante_id bigint, primary key (id)) engine=InnoDB;
create table tab_restaurante (id bigint not null auto_increment, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_completo varchar(255), endereco_cep varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255), taxa_frete decimal(19,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id)) engine=InnoDB;
create table tab_usuario (id bigint not null auto_increment, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null) engine=InnoDB;
alter table permissao_grupo add constraint FKonc7s92tu3s5qy3d7qtju9t4c foreign key (grupo_id) references tab_grupo (id);
alter table permissao_grupo add constraint FKjiwy96fpjkp8yg0vair0ueydw foreign key (permissao_id) references tab_permissao (id);
alter table restaurante_forma_pagamento add constraint FKixtv47n90rd3yfq44fq11bmcv foreign key (forma_pagamento_id) references tab_forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKq7kobci8cnwfdkqut2oci463v foreign key (restaurante_id) references tab_restaurante (id);
alter table tab_cidade add constraint FK4b6sgc0n0yyygn88op23j2bu foreign key (estado_id) references tab_estado (id);
alter table tab_produto add constraint FK45nn2ff5303j5ffcroswba5bx foreign key (produto_restaurante_id) references tab_restaurante (id);
alter table tab_restaurante add constraint FKco69opd16s0dafppqa69e5snn foreign key (cozinha_id) references tab_cozinha (id);
alter table tab_restaurante add constraint FKc38xcl49t59w9utt67nucwiq3 foreign key (endereco_cidade_id) references tab_cidade (id);
alter table usuario_grupo add constraint FKkgqukhil46thvx3mvgjls73c0 foreign key (grupo_id) references tab_grupo (id);
alter table usuario_grupo add constraint FKhgy6npots9lv9yclufie4riip foreign key (usuario_id) references tab_usuario (id);
insert into tab_cozinha (nom_cozinha) values ('Iailandesa');
insert into tab_cozinha (nom_cozinha) values ('Indiana');
insert into tab_estado(nome) values('São Paulo');
insert into tab_cidade(nome, estado_id)values("Caçapava", 1);
insert into tab_forma_pagamento(descricao) values ('Cartão de crédito');
insert into tab_forma_pagamento(descricao) values ('débito');
insert into tab_forma_pagamento(descricao) values ('dinheiro');
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('tudo nosso', 156, 2, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('nada consta', 200, 1, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('sete a um', 300, 1, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_completo, endereco_cep, endereco_numero, endereco_logradouro, data_cadastro, data_atualizacao) values ('Frans Leste', 200, 1, 1, 'parque sírio', '03562523', '362', 'Rua Jose maturatto', utc_timestamp, utc_timestamp);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id)values(1,1);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id)values(1,2);
create table permissao_grupo (permissao_id bigint not null, grupo_id bigint not null) engine=InnoDB;
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null) engine=InnoDB;
create table tab_cidade (id bigint not null auto_increment, nome varchar(255), estado_id bigint not null, primary key (id)) engine=InnoDB;
create table tab_cozinha (id bigint not null auto_increment, observacao varchar(255), nom_cozinha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tab_estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table tab_forma_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table tab_grupo (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table tab_permissao (id bigint not null auto_increment, descricao varchar(255), nom_permissao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tab_produto (id bigint not null auto_increment, ativo bit, descricao varchar(255), preco decimal(19,2), produto_restaurante_id bigint, primary key (id)) engine=InnoDB;
create table tab_restaurante (id bigint not null auto_increment, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_completo varchar(255), endereco_cep varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255), taxa_frete decimal(19,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id)) engine=InnoDB;
create table tab_usuario (id bigint not null auto_increment, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null) engine=InnoDB;
alter table permissao_grupo add constraint FKonc7s92tu3s5qy3d7qtju9t4c foreign key (grupo_id) references tab_grupo (id);
alter table permissao_grupo add constraint FKjiwy96fpjkp8yg0vair0ueydw foreign key (permissao_id) references tab_permissao (id);
alter table restaurante_forma_pagamento add constraint FKixtv47n90rd3yfq44fq11bmcv foreign key (forma_pagamento_id) references tab_forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKq7kobci8cnwfdkqut2oci463v foreign key (restaurante_id) references tab_restaurante (id);
alter table tab_cidade add constraint FK4b6sgc0n0yyygn88op23j2bu foreign key (estado_id) references tab_estado (id);
alter table tab_produto add constraint FK45nn2ff5303j5ffcroswba5bx foreign key (produto_restaurante_id) references tab_restaurante (id);
alter table tab_restaurante add constraint FKco69opd16s0dafppqa69e5snn foreign key (cozinha_id) references tab_cozinha (id);
alter table tab_restaurante add constraint FKc38xcl49t59w9utt67nucwiq3 foreign key (endereco_cidade_id) references tab_cidade (id);
alter table usuario_grupo add constraint FKkgqukhil46thvx3mvgjls73c0 foreign key (grupo_id) references tab_grupo (id);
alter table usuario_grupo add constraint FKhgy6npots9lv9yclufie4riip foreign key (usuario_id) references tab_usuario (id);
insert into tab_cozinha (nom_cozinha) values ('Iailandesa');
insert into tab_cozinha (nom_cozinha) values ('Indiana');
insert into tab_estado(nome) values('São Paulo');
insert into tab_cidade(nome, estado_id)values("Caçapava", 1);
insert into tab_forma_pagamento(descricao) values ('Cartão de crédito');
insert into tab_forma_pagamento(descricao) values ('débito');
insert into tab_forma_pagamento(descricao) values ('dinheiro');
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('tudo nosso', 156, 2, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('nada consta', 200, 1, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('sete a um', 300, 1, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_completo, endereco_cep, endereco_numero, endereco_logradouro, data_cadastro, data_atualizacao) values ('Frans Leste', 200, 1, 1, 'parque sírio', '03562523', '362', 'Rua Jose maturatto', utc_timestamp, utc_timestamp);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id)values(1,1);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id)values(1,2);
create table permissao_grupo (permissao_id bigint not null, grupo_id bigint not null) engine=InnoDB;
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null) engine=InnoDB;
create table tab_cidade (id bigint not null auto_increment, nome varchar(255), estado_id bigint not null, primary key (id)) engine=InnoDB;
create table tab_cozinha (id bigint not null auto_increment, observacao varchar(255), nom_cozinha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tab_estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table tab_forma_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table tab_grupo (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table tab_permissao (id bigint not null auto_increment, descricao varchar(255), nom_permissao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tab_produto (id bigint not null auto_increment, ativo bit, descricao varchar(255), preco decimal(19,2), produto_restaurante_id bigint, primary key (id)) engine=InnoDB;
create table tab_restaurante (id bigint not null auto_increment, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_completo varchar(255), endereco_cep varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255), taxa_frete decimal(19,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id)) engine=InnoDB;
create table tab_usuario (id bigint not null auto_increment, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null) engine=InnoDB;
alter table permissao_grupo add constraint FKonc7s92tu3s5qy3d7qtju9t4c foreign key (grupo_id) references tab_grupo (id);
alter table permissao_grupo add constraint FKjiwy96fpjkp8yg0vair0ueydw foreign key (permissao_id) references tab_permissao (id);
alter table restaurante_forma_pagamento add constraint FKixtv47n90rd3yfq44fq11bmcv foreign key (forma_pagamento_id) references tab_forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKq7kobci8cnwfdkqut2oci463v foreign key (restaurante_id) references tab_restaurante (id);
alter table tab_cidade add constraint FK4b6sgc0n0yyygn88op23j2bu foreign key (estado_id) references tab_estado (id);
alter table tab_produto add constraint FK45nn2ff5303j5ffcroswba5bx foreign key (produto_restaurante_id) references tab_restaurante (id);
alter table tab_restaurante add constraint FKco69opd16s0dafppqa69e5snn foreign key (cozinha_id) references tab_cozinha (id);
alter table tab_restaurante add constraint FKc38xcl49t59w9utt67nucwiq3 foreign key (endereco_cidade_id) references tab_cidade (id);
alter table usuario_grupo add constraint FKkgqukhil46thvx3mvgjls73c0 foreign key (grupo_id) references tab_grupo (id);
alter table usuario_grupo add constraint FKhgy6npots9lv9yclufie4riip foreign key (usuario_id) references tab_usuario (id);
insert into tab_cozinha (nom_cozinha) values ('Iailandesa');
insert into tab_cozinha (nom_cozinha) values ('Indiana');
insert into tab_estado(nome) values('São Paulo');
insert into tab_cidade(nome, estado_id)values("Caçapava", 1);
insert into tab_forma_pagamento(descricao) values ('Cartão de crédito');
insert into tab_forma_pagamento(descricao) values ('débito');
insert into tab_forma_pagamento(descricao) values ('dinheiro');
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('tudo nosso', 156, 2, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('nada consta', 200, 1, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('sete a um', 300, 1, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_completo, endereco_cep, endereco_numero, endereco_logradouro, data_cadastro, data_atualizacao) values ('Frans Leste', 200, 1, 1, 'parque sírio', '03562523', '362', 'Rua Jose maturatto', utc_timestamp, utc_timestamp);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id)values(1,1);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id)values(1,2);
create table permissao_grupo (permissao_id bigint not null, grupo_id bigint not null) engine=InnoDB;
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null) engine=InnoDB;
create table tab_cidade (id bigint not null auto_increment, nome varchar(255), estado_id bigint not null, primary key (id)) engine=InnoDB;
create table tab_cozinha (id bigint not null auto_increment, observacao varchar(255), nom_cozinha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tab_estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table tab_forma_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table tab_grupo (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table tab_permissao (id bigint not null auto_increment, descricao varchar(255), nom_permissao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tab_produto (id bigint not null auto_increment, ativo bit, descricao varchar(255), preco decimal(19,2), produto_restaurante_id bigint, primary key (id)) engine=InnoDB;
create table tab_restaurante (id bigint not null auto_increment, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_completo varchar(255), endereco_cep varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255), taxa_frete decimal(19,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id)) engine=InnoDB;
create table tab_usuario (id bigint not null auto_increment, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null) engine=InnoDB;
alter table permissao_grupo add constraint FKonc7s92tu3s5qy3d7qtju9t4c foreign key (grupo_id) references tab_grupo (id);
alter table permissao_grupo add constraint FKjiwy96fpjkp8yg0vair0ueydw foreign key (permissao_id) references tab_permissao (id);
alter table restaurante_forma_pagamento add constraint FKixtv47n90rd3yfq44fq11bmcv foreign key (forma_pagamento_id) references tab_forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKq7kobci8cnwfdkqut2oci463v foreign key (restaurante_id) references tab_restaurante (id);
alter table tab_cidade add constraint FK4b6sgc0n0yyygn88op23j2bu foreign key (estado_id) references tab_estado (id);
alter table tab_produto add constraint FK45nn2ff5303j5ffcroswba5bx foreign key (produto_restaurante_id) references tab_restaurante (id);
alter table tab_restaurante add constraint FKco69opd16s0dafppqa69e5snn foreign key (cozinha_id) references tab_cozinha (id);
alter table tab_restaurante add constraint FKc38xcl49t59w9utt67nucwiq3 foreign key (endereco_cidade_id) references tab_cidade (id);
alter table usuario_grupo add constraint FKkgqukhil46thvx3mvgjls73c0 foreign key (grupo_id) references tab_grupo (id);
alter table usuario_grupo add constraint FKhgy6npots9lv9yclufie4riip foreign key (usuario_id) references tab_usuario (id);
insert into tab_cozinha (nom_cozinha) values ('Iailandesa');
insert into tab_cozinha (nom_cozinha) values ('Indiana');
insert into tab_estado(nome) values('São Paulo');
insert into tab_cidade(nome, estado_id)values("Caçapava", 1);
insert into tab_forma_pagamento(descricao) values ('Cartão de crédito');
insert into tab_forma_pagamento(descricao) values ('débito');
insert into tab_forma_pagamento(descricao) values ('dinheiro');
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('tudo nosso', 156, 2, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('nada consta', 200, 1, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('sete a um', 300, 1, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_completo, endereco_cep, endereco_numero, endereco_logradouro, data_cadastro, data_atualizacao) values ('Frans Leste', 200, 1, 1, 'parque sírio', '03562523', '362', 'Rua Jose maturatto', utc_timestamp, utc_timestamp);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id)values(1,1);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id)values(1,2);
create table permissao_grupo (permissao_id bigint not null, grupo_id bigint not null) engine=InnoDB;
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null) engine=InnoDB;
create table tab_cidade (id bigint not null auto_increment, nome varchar(255), estado_id bigint not null, primary key (id)) engine=InnoDB;
create table tab_cozinha (id bigint not null auto_increment, observacao varchar(255), nom_cozinha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tab_estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table tab_forma_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table tab_grupo (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table tab_permissao (id bigint not null auto_increment, descricao varchar(255), nom_permissao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tab_produto (id bigint not null auto_increment, ativo bit, descricao varchar(255), preco decimal(19,2), produto_restaurante_id bigint, primary key (id)) engine=InnoDB;
create table tab_restaurante (id bigint not null auto_increment, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_completo varchar(255), endereco_cep varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255), taxa_frete decimal(19,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id)) engine=InnoDB;
create table tab_usuario (id bigint not null auto_increment, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null) engine=InnoDB;
alter table permissao_grupo add constraint FKonc7s92tu3s5qy3d7qtju9t4c foreign key (grupo_id) references tab_grupo (id);
alter table permissao_grupo add constraint FKjiwy96fpjkp8yg0vair0ueydw foreign key (permissao_id) references tab_permissao (id);
alter table restaurante_forma_pagamento add constraint FKixtv47n90rd3yfq44fq11bmcv foreign key (forma_pagamento_id) references tab_forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKq7kobci8cnwfdkqut2oci463v foreign key (restaurante_id) references tab_restaurante (id);
alter table tab_cidade add constraint FK4b6sgc0n0yyygn88op23j2bu foreign key (estado_id) references tab_estado (id);
alter table tab_produto add constraint FK45nn2ff5303j5ffcroswba5bx foreign key (produto_restaurante_id) references tab_restaurante (id);
alter table tab_restaurante add constraint FKco69opd16s0dafppqa69e5snn foreign key (cozinha_id) references tab_cozinha (id);
alter table tab_restaurante add constraint FKc38xcl49t59w9utt67nucwiq3 foreign key (endereco_cidade_id) references tab_cidade (id);
alter table usuario_grupo add constraint FKkgqukhil46thvx3mvgjls73c0 foreign key (grupo_id) references tab_grupo (id);
alter table usuario_grupo add constraint FKhgy6npots9lv9yclufie4riip foreign key (usuario_id) references tab_usuario (id);
insert into tab_cozinha (nom_cozinha) values ('Iailandesa');
insert into tab_cozinha (nom_cozinha) values ('Indiana');
insert into tab_estado(nome) values('São Paulo');
insert into tab_cidade(nome, estado_id)values("Caçapava", 1);
insert into tab_forma_pagamento(descricao) values ('Cartão de crédito');
insert into tab_forma_pagamento(descricao) values ('débito');
insert into tab_forma_pagamento(descricao) values ('dinheiro');
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('tudo nosso', 156, 2, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('nada consta', 200, 1, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('sete a um', 300, 1, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_completo, endereco_cep, endereco_numero, endereco_logradouro, data_cadastro, data_atualizacao) values ('Frans Leste', 200, 1, 1, 'parque sírio', '03562523', '362', 'Rua Jose maturatto', utc_timestamp, utc_timestamp);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id)values(1,1);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id)values(1,2);
create table permissao_grupo (permissao_id bigint not null, grupo_id bigint not null) engine=InnoDB;
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null) engine=InnoDB;
create table tab_cidade (id bigint not null auto_increment, nome varchar(255), estado_id bigint not null, primary key (id)) engine=InnoDB;
create table tab_cozinha (id bigint not null auto_increment, observacao varchar(255), nom_cozinha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tab_estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table tab_forma_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table tab_grupo (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table tab_permissao (id bigint not null auto_increment, descricao varchar(255), nom_permissao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tab_produto (id bigint not null auto_increment, ativo bit, descricao varchar(255), preco decimal(19,2), produto_restaurante_id bigint, primary key (id)) engine=InnoDB;
create table tab_restaurante (id bigint not null auto_increment, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_completo varchar(255), endereco_cep varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255), taxa_frete decimal(19,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id)) engine=InnoDB;
create table tab_usuario (id bigint not null auto_increment, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null) engine=InnoDB;
alter table permissao_grupo add constraint FKonc7s92tu3s5qy3d7qtju9t4c foreign key (grupo_id) references tab_grupo (id);
alter table permissao_grupo add constraint FKjiwy96fpjkp8yg0vair0ueydw foreign key (permissao_id) references tab_permissao (id);
alter table restaurante_forma_pagamento add constraint FKixtv47n90rd3yfq44fq11bmcv foreign key (forma_pagamento_id) references tab_forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKq7kobci8cnwfdkqut2oci463v foreign key (restaurante_id) references tab_restaurante (id);
alter table tab_cidade add constraint FK4b6sgc0n0yyygn88op23j2bu foreign key (estado_id) references tab_estado (id);
alter table tab_produto add constraint FK45nn2ff5303j5ffcroswba5bx foreign key (produto_restaurante_id) references tab_restaurante (id);
alter table tab_restaurante add constraint FKco69opd16s0dafppqa69e5snn foreign key (cozinha_id) references tab_cozinha (id);
alter table tab_restaurante add constraint FKc38xcl49t59w9utt67nucwiq3 foreign key (endereco_cidade_id) references tab_cidade (id);
alter table usuario_grupo add constraint FKkgqukhil46thvx3mvgjls73c0 foreign key (grupo_id) references tab_grupo (id);
alter table usuario_grupo add constraint FKhgy6npots9lv9yclufie4riip foreign key (usuario_id) references tab_usuario (id);
insert into tab_cozinha (nom_cozinha) values ('Iailandesa');
insert into tab_cozinha (nom_cozinha) values ('Indiana');
insert into tab_estado(nome) values('São Paulo');
insert into tab_cidade(nome, estado_id)values("Caçapava", 1);
insert into tab_forma_pagamento(descricao) values ('Cartão de crédito');
insert into tab_forma_pagamento(descricao) values ('débito');
insert into tab_forma_pagamento(descricao) values ('dinheiro');
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('tudo nosso', 156, 2, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('nada consta', 200, 1, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('sete a um', 300, 1, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_completo, endereco_cep, endereco_numero, endereco_logradouro, data_cadastro, data_atualizacao) values ('Frans Leste', 200, 1, 1, 'parque sírio', '03562523', '362', 'Rua Jose maturatto', utc_timestamp, utc_timestamp);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id)values(1,1);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id)values(1,2);
create table permissao_grupo (permissao_id bigint not null, grupo_id bigint not null) engine=InnoDB;
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null) engine=InnoDB;
create table tab_cidade (id bigint not null auto_increment, nome varchar(255), estado_id bigint not null, primary key (id)) engine=InnoDB;
create table tab_cozinha (id bigint not null auto_increment, observacao varchar(255), nom_cozinha varchar(255) not null, primary key (id)) engine=InnoDB;
create table tab_estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table tab_forma_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table tab_grupo (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table tab_permissao (id bigint not null auto_increment, descricao varchar(255), nom_permissao varchar(255) not null, primary key (id)) engine=InnoDB;
create table tab_produto (id bigint not null auto_increment, ativo bit, descricao varchar(255), preco decimal(19,2), produto_restaurante_id bigint, primary key (id)) engine=InnoDB;
create table tab_restaurante (id bigint not null auto_increment, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_completo varchar(255), endereco_cep varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255), taxa_frete decimal(19,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id)) engine=InnoDB;
create table tab_usuario (id bigint not null auto_increment, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null) engine=InnoDB;
alter table permissao_grupo add constraint FKonc7s92tu3s5qy3d7qtju9t4c foreign key (grupo_id) references tab_grupo (id);
alter table permissao_grupo add constraint FKjiwy96fpjkp8yg0vair0ueydw foreign key (permissao_id) references tab_permissao (id);
alter table restaurante_forma_pagamento add constraint FKixtv47n90rd3yfq44fq11bmcv foreign key (forma_pagamento_id) references tab_forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKq7kobci8cnwfdkqut2oci463v foreign key (restaurante_id) references tab_restaurante (id);
alter table tab_cidade add constraint FK4b6sgc0n0yyygn88op23j2bu foreign key (estado_id) references tab_estado (id);
alter table tab_produto add constraint FK45nn2ff5303j5ffcroswba5bx foreign key (produto_restaurante_id) references tab_restaurante (id);
alter table tab_restaurante add constraint FKco69opd16s0dafppqa69e5snn foreign key (cozinha_id) references tab_cozinha (id);
alter table tab_restaurante add constraint FKc38xcl49t59w9utt67nucwiq3 foreign key (endereco_cidade_id) references tab_cidade (id);
alter table usuario_grupo add constraint FKkgqukhil46thvx3mvgjls73c0 foreign key (grupo_id) references tab_grupo (id);
alter table usuario_grupo add constraint FKhgy6npots9lv9yclufie4riip foreign key (usuario_id) references tab_usuario (id);
insert into tab_cozinha (nom_cozinha) values ('Iailandesa');
insert into tab_cozinha (nom_cozinha) values ('Indiana');
insert into tab_estado(nome) values('São Paulo');
insert into tab_cidade(nome, estado_id)values("Caçapava", 1);
insert into tab_forma_pagamento(descricao) values ('Cartão de crédito');
insert into tab_forma_pagamento(descricao) values ('débito');
insert into tab_forma_pagamento(descricao) values ('dinheiro');
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('tudo nosso', 156, 2, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('nada consta', 200, 1, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('sete a um', 300, 1, utc_timestamp, utc_timestamp);
insert into tab_restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_completo, endereco_cep, endereco_numero, endereco_logradouro, data_cadastro, data_atualizacao) values ('Frans Leste', 200, 1, 1, 'parque sírio', '03562523', '362', 'Rua Jose maturatto', utc_timestamp, utc_timestamp);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id)values(1,1);
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id)values(1,2);
